### PR TITLE
fix unicode normalization

### LINKED ISSUE #153: f-string-parser: Fix test_format_specifier_expressions
In `test_fstring` the test `test_format_specifier_expressions` is failing with:

```
ERROR: test_format_specifier_expressions (test.test_fstring.TestCase) (str="f'result: {value:{width:{0}}.{precision:1}}'")\n----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pablogsal/github/python/f-string-grammar/Lib/test/test_fstring.py", line 33, in assertAllRaise
    eval(str)
    ^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'value' is not defined
```

### PR DESCRIPTION
**Pull request by isidentical**
Fixes #153, #154, #156 (i think), #160, #166

### CODE REVIEW

File: Parser/pegen.c [hunk 1]
```diff
@@ -2661,7 +2661,9 @@ expr_ty _PyPegen_collect_call_seqs(Parser *p, asdl_expr_seq *a, asdl_seq *b,
 
 static expr_ty
 _PyPegen_fstring_bytes_constant_to_unicode(Parser* p, int is_raw, expr_ty constant) {
```
Comment (pablogsal) [inline Parser/pegen.c]: The name of the function needs update then :)

Comment (isidentical) [reply Parser/pegen.c]: I've renamed this to something that makes more sense, hopefully it should be more clear now.

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Thanks @isidentical !!
