### PR TITLE
Ignore encoding cookie when that's necessary

### LINKED ISSUE #63: Failure in test_compile: Unexpected LookupError
Current Parser:
```
╰─ ./python       
Python 3.9.0a5+ (heads/pegen:99a8e2fa08, Apr  9 2020, 16:19:04) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> code = '# -*- coding: badencoding -*-\n"\xc2\xa4"\n'
>>> eval(code)
'Â¤'
```

Pegen:
```
╰─ ./python -p new
Python 3.9.0a5+ (heads/pegen:99a8e2fa08, Apr  9 2020, 16:19:04) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> code = '# -*- coding: badencoding -*-\n"\xc2\xa4"\n'
>>> eval(code)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
LookupError: unknown encoding: badencoding
```

### PR DESCRIPTION
**Pull request by lysnikolaou**
Pass the compiler flags down the chain of function calls, so that pegen knows if it has to ignore the encoding or not.

Closes #63.

### CODE REVIEW

**Comment by lysnikolaou** [comment]
This breaks test_embed with a segmentation fault and I can't figure out why.

File: Parser/pegen/pegen.c [hunk 1]
```diff
@@ -814,10 +814,10 @@ run_parser_from_file(const char *filename, int start_rule,
 
 mod_ty
 run_parser_from_string(const char *str, int start_rule, PyObject *filename_ob,
-                       PyCompilerFlags *flags, PyArena *arena)
+                       int flags, PyArena *arena)
```
Comment (gvanrossum) [inline Parser/pegen/pegen.c:817]: I recommend rename the argument `iflags`.
